version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "3180:80"
        volumes:
            - ./deployment/local/docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        links:
            - php-fpm
        depends_on:
            - php-fpm
    php-fpm:
        build: ./deployment/local/docker/php-fpm
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - ./:/var/www
    mysql:
        image: mysql:latest
        ports:
            - "8306:3306"
        volumes:
            - ./persistent_data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=project
