version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "3180:80"
        volumes:
            - ./deployment/local/docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        links:
            - php-fpm
        depends_on:
            - php-fpm
    php-fpm:
        build: ./deployment/local/docker/php-fpm
        container_name: php-fpm
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - ./:/var/www
    mysql:
        image: percona:latest
        container_name: db-master
        ports:
            - "8306:3306"
        volumes:
            - ./deployment/local/docker/mysql/config/master.cnf:/etc/my.cnf.d/repl.cnf
            - ./deployment/local/docker/mysql/config/master.sql:/docker-entrypoint-initdb.d/start.sql
            #- ./persistent_data/master:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_DATABASE=project
    mysqlread1:
        image: percona:latest
        container_name: db-slave1
        ports:
            - "8307:3306"
        volumes:
            - ./deployment/local/docker/mysql/config/slave1.cnf:/etc/my.cnf.d/repl.cnf
            - ./deployment/local/docker/mysql/config/slave.sql:/docker-entrypoint-initdb.d/start.sql
            #- ./persistent_data/slave1:/var/lib/mysql
        depends_on:
            - mysql
        environment:
          - MYSQL_ROOT_PASSWORD=secret
    mysqlread2:
        image: percona:latest
        container_name: db-slave2
        ports:
            - "8308:3306"
        volumes:
            - ./deployment/local/docker/mysql/config/slave2.cnf:/etc/my.cnf.d/repl.cnf
            - ./deployment/local/docker/mysql/config/slave.sql:/docker-entrypoint-initdb.d/start.sql
            #- ./persistent_data/slave2:/var/lib/mysql
        depends_on:
            - mysql
        environment:
          - MYSQL_ROOT_PASSWORD=secret